language: cpp

before_install:
  - wget http://sourceforge.net/projects/devkitpro/files/Automated%20Installer/devkitARMupdate.pl
  - export DEVKITPRO=/home/travis/devkitPro
  - export DEVKITARM=${DEVKITPRO}/devkitARM

install:
  - sudo perl devkitARMupdate.pl
  - wget --no-check-certificate https://codeload.github.com/ahezard/libnds/zip/master -O /tmp/libnds.zip
  - unzip /tmp/libnds.zip
  - cd libnds-master
  - make && sudo make install
  - cd ..

script:
  - make
  - bash build_cia.sh
  
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - libstdc++6

after_success:
  - >
    if [ "$TRAVIS_BRANCH" == "master" ]; then
        GITDATE="`git show -s --date=short --format='%ad' | sed 's/-//g'`"
        GITREV="`git show -s --format='%h'`"
        REV_NAME="bootstrap-dldi-${GITDATE}-${GITREV}.nds"
        cp bootstrap-dldi.nds $REV_NAME
        lftp -c "open -u nds-bootstrap,$BUILD_PASSWORD sftp://joshuadoes.com; put -O ' /home/nds-bootstrap' '${REV_NAME}'"
    fi